'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating shipping quotes based on shipment details.
 *
 * It includes the function `generateShippingQuote` which takes shipment details as input
 * and returns a shipping quotation generated by AI.
 *
 * @exports generateShippingQuote - The function to generate shipping quotes.
 * @exports GenerateShippingQuoteInput - The input type for the generateShippingQuote function.
 * @exports GenerateShippingQuoteOutput - The output type for the generateShippingQuote function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateShippingQuoteInputSchema = z.object({
  destination: z.string().describe('The destination of the shipment.'),
  weight: z.number().describe('The weight of the shipment in kilograms.'),
  length: z.number().describe('The length of the shipment in centimeters.'),
  width: z.number().describe('The width of the shipment in centimeters.'),
  height: z.number().describe('The height of the shipment in centimeters.'),
  transportationType: z
    .string()
    .describe(
      'The transportation type such as maritime, air, or road. Consider transportation type such as maritime.'
    ),
});
export type GenerateShippingQuoteInput = z.infer<typeof GenerateShippingQuoteInputSchema>;

const GenerateShippingQuoteOutputSchema = z.object({
  quote: z.string().describe('The generated shipping quotation.'),
});
export type GenerateShippingQuoteOutput = z.infer<typeof GenerateShippingQuoteOutputSchema>;

export async function generateShippingQuote(input: GenerateShippingQuoteInput): Promise<GenerateShippingQuoteOutput> {
  return generateShippingQuoteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateShippingQuotePrompt',
  input: {schema: GenerateShippingQuoteInputSchema},
  output: {schema: GenerateShippingQuoteOutputSchema},
  prompt: `You are a shipping expert. You will generate a shipping quote based on the provided shipment details.  Consider transportation type such as maritime.

Shipment Details:
Destination: {{{destination}}}
Weight: {{{weight}}} kg
Dimensions: {{{length}}}cm x {{{width}}}cm x {{{height}}}cm
Transportation Type: {{{transportationType}}}

Generate a shipping quote:`,
});

const generateShippingQuoteFlow = ai.defineFlow(
  {
    name: 'generateShippingQuoteFlow',
    inputSchema: GenerateShippingQuoteInputSchema,
    outputSchema: GenerateShippingQuoteOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
